spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sam-mmm/spring-tutorial.git
          search-paths:
            - configurations
          default-label: 09-circuit-breaker-resilience4j-time-limiter
          clone-on-start: true