spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/sam-mmm/spring-tutorial.git
          search-paths:
            - configurations
          default-label: 08-resilience4j-rate-limiter
          clone-on-start: true